name: iPXE Build
on:
  push:
    branches:
    - main

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build iPXE
      run: (env; cd binary/; export GITHUB_TOKEN=${TOKEN}; ./script/orchestrate.sh)
    